name: 'action-github-docker-build'
description: 'Build and push docker images'
author: 'PlayStudios'
inputs:
  registry:
    required: true
    description: 'The docker registry to push to'
  username:
    required: false
    description: 'The username to use for logging into the docker registry'
  password:
    required: false
    description: 'The password to use for logging into the docker registry'
  tag:
    required: true
    description: 'The image tag. Recommended to use ${{ github.sha }}'
  build_args:
    required: false
    description: 'Comma (,) separated list of environment variables to set as --build-arg'
  dockerfile:
    required: false
    default: 'Dockerfile'
    description: 'The Dockerfile to use'
  build_context:
    required: false
    default: '.'
    description: 'Docker build context'
runs:
  using: 'node12'
  main: 'dist/index.js'
